### ISSUE TITLE
Pod cost-analyzer initial restart - Part 2

### ISSUE THREAD

**Issue by pierluigilenoci** [opencost/opencost#1111]
For no apparent reason (other than updating to the latest version, from 1.90.1 to 1.91.0) the pod started going into CrashLoopBack. 
Not related to #1107 

```shell
kubectl logs -n [REDACTED] -l app=cost-analyzer
github.com/spf13/cobra.(*Command).ExecuteC(0xc0008fcf00)
	/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/kubecost/cost-model/pkg/cmd.Execute(0xc00005c060)
	/app/cost-model/pkg/cmd/commands.go:63 +0x325
github.com/kubecost/kubecost-cost-model/pkg/cmd.Execute()
	/app/kubecost-cost-model/pkg/cmd/commands.go:17 +0x1e
main.main()
	/app/kubecost-cost-model/cmd/costmodel/main.go:13 +0x19
```

If there is any further information you need just ask.

Thanks in advance.

gz#1509

**Comment by kbrwn** [comment]
hello @pierluigilenoci thanks for reporting this. We need a bug report or the logs of the cost-model container within the kubecost-cost-analyzer pod. You probably want to append `--previous` if you fetch this data with `kubectl logs` cmd. You can email these logs to support@kubecost.com if you prefer not to share publicly.

**Comment by pierluigilenoci** [comment]
@kbrwn I get the same result:

```
kubectl logs -n [REDACTED]-l app=cost-analyzer --previous
github.com/spf13/cobra.(*Command).ExecuteC(0xc000986280)
	/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/kubecost/cost-model/pkg/cmd.Execute(0xc000102000)
	/app/cost-model/pkg/cmd/commands.go:63 +0x325
github.com/kubecost/kubecost-cost-model/pkg/cmd.Execute()
	/app/kubecost-cost-model/pkg/cmd/commands.go:17 +0x1e
main.main()
	/app/kubecost-cost-model/cmd/costmodel/main.go:13 +0x19
```

```
kubectl get pods -n [REDACTED]
NAMESPACE             NAME                                                            READY   STATUS             RESTARTS   AGE
k8s-kubecost          cost-analyzer-55878f556f-sxzjq                                  0/3     CrashLoopBackOff   17         66m
```

**Comment by kbrwn** [comment]
hi @pierluigilenoci Did you modify any of the `command` or `arg` options in any deployments?

**Comment by pierluigilenoci** [comment]
@kbrwn these are the complete values with which the chart has been deployed:

```yaml
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - eu-west-1a
global:
  grafana:
    domainName: [REDACTED]
    enabled: false
    proxy: false
    scheme: https
    sidecar:
      datasources:
        enabled: false
  notifications:
    alertConfigs:
      alerts: []
      enabled: true
      frontendUrl: https://[REDACTED]
      globalAlertEmails:
      - [REDACTED]
      globalSlackWebhookUrl: https://hooks.slack.com/services/[REDACTED]
      kubecostHealth: true
  podAnnotations:
    kubectl.kubernetes.io/default-container: cost-model
  prometheus:
    enabled: false
    fqdn: http://[REDACTED]
grafana:
  sidecar:
    dashboards:
      enabled: false
ingress:
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/whitelist-source-range: [REDACTED]
  className: nginx
  enabled: true
  hosts:
  - [REDACTED]
  tls:
  - hosts:
    - [REDACTED]
    secretName: [REDACTED]
kubecost:
  resources:
    requests:
      cpu: 10m
      memory: 64.8Mi
kubecostFrontend:
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 10m
      memory: 19.1Mi
  tls:
    enabled: false
kubecostModel:
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 374.8Mi
kubecostProductConfigs:
  athenaBucketName: s3://[REDACTED]
  athenaDatabase: [REDACTED]
  athenaProjectID: [REDACTED]
  athenaRegion: eu-west-1
  athenaTable: [REDACTED]
  clusterName: [REDACTED]
  clusterProfile: production
  currencyCode: EUR
  defaultIdle: true
  grafanaURL: https://[REDACTED]
  labelMappingConfigs:
    cluster_external_label: [REDACTED]
    department_external_label: [REDACTED]
    department_label: [REDACTED]
    enabled: true
    environment_external_label: [REDACTED]
    environment_label: [REDACTED]
    namespace_external_label: kubernetes.io/created-for/pvc/namespace
    product_external_label: [REDACTED]
    product_label: [REDACTED]
    team_external_label: [REDACTED]
    team_label: [REDACTED]
  masterPayerARN: arn:aws:iam::[REDACTED]:role/[REDACTED]
  projectID: [REDACTED]
  serviceKeySecretName: [REDACTED]
  sharedNamespaces: default,[REDACTED],kube-node-lease,kube-public,kube-system,[REDACTED]
kubecostToken: [REDACTED]
networkCosts:
  enabled: true
  imagePullPolicy: IfNotPresent
  podSecurityPolicy:
    enabled: true
  priorityClassName: addon-priority
  prometheusScrape: true
  resources:
    requests:
      cpu: 94m
      memory: 99.2Mi
  services:
    amazon-web-services: true
    azure-cloud-services: true
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoExecute
    operator: Exists
  - effect: NoSchedule
    operator: Exists
  - effect: PreferNoSchedule
    operator: Exists
  trafficLogging: true
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 5
networkPolicy:
  costAnalyzer:
    enabled: true
  denyEgress: false
  enabled: true
  namespace: [REDACTED]
  sameNamespace: false
nodeSelector:
  node-selector-key: system
persistentVolume:
  storageClass: eu-west-1a
podSecurityPolicy:
  enabled: true
priority:
  enabled: true
  value: 999999
prometheus:
  kube-state-metrics:
    disabled: true
  server:
    global:
      external_labels:
        cluster_id: [REDACTED]
tolerations:
- key: CriticalAddonsOnly
  operator: Exists
```

**Comment by pierluigilenoci** [comment]
I have done some tests, tried to update to version 1.91.1 and I get the same error.
If, on the other hand, I roll back to 1.90.1 everything works perfectly.

Ref: https://github.com/kubecost/cost-model/compare/v1.90.1...v1.91.0

We have clusters on both AKS and EKS.
The problem occurs only on AWS, on Azure it works perfectly.

**Comment by pierluigilenoci** [comment]
I was able to get a more comprehensive log:

```shell
I0315 10:21:07.896598       1 router.go:1319] Starting cost-model (git commit "1.91.0")
I0315 10:21:07.896699       1 router.go:1342] Prometheus/Thanos Client Max Concurrency set to 5
I0315 10:21:07.916778       1 router.go:1383] Success: retrieved the 'up' query against prometheus at: http://[REDACTED]
I0315 10:21:07.925216       1 router.go:1391] Retrieved a prometheus config file from: http://[REDACTED]
I0315 10:21:07.934483       1 router.go:1400] Using scrape interval of 60.000000
I0315 10:21:07.944331       1 clustercache.go:114] NAMESPACE: [REDACTED]
I0315 10:21:08.546382       1 clustercache.go:161] Done waiting
I0315 10:21:08.547205       1 watchcontroller.go:195] Starting *v1.Namespace controller
I0315 10:21:08.547362       1 watchcontroller.go:195] Starting *v1.Node controller
I0315 10:21:08.547428       1 watchcontroller.go:195] Starting *v1.Pod controller
I0315 10:21:08.547551       1 watchcontroller.go:195] Starting *v1.Service controller
I0315 10:21:08.547599       1 watchcontroller.go:195] Starting *v1.ConfigMap controller
I0315 10:21:08.547673       1 watchcontroller.go:195] Starting *v1.DaemonSet controller
I0315 10:21:08.547701       1 watchcontroller.go:195] Starting *v1.Deployment controller
I0315 10:21:08.547773       1 watchcontroller.go:195] Starting *v1.StatefulSet controller
I0315 10:21:08.547794       1 watchcontroller.go:195] Starting *v1.ReplicaSet controller
I0315 10:21:08.547929       1 watchcontroller.go:195] Starting *v1.PersistentVolume controller
I0315 10:21:08.548000       1 watchcontroller.go:195] Starting *v1.PersistentVolumeClaim controller
I0315 10:21:08.548031       1 watchcontroller.go:195] Starting *v1.StorageClass controller
I0315 10:21:08.548068       1 watchcontroller.go:195] Starting *v1.Job controller
I0315 10:21:08.548081       1 watchcontroller.go:195] Starting *v2beta1.HorizontalPodAutoscaler controller
I0315 10:21:08.548104       1 watchcontroller.go:195] Starting *v1beta1.PodDisruptionBudget controller
I0315 10:21:08.548118       1 watchcontroller.go:195] Starting *v1.ReplicationController controller
I0315 10:21:08.549106       1 provider.go:452] Found ProviderID starting with "aws", using AWS Provider
I0315 10:21:08.557082       1 router.go:1452] No asset-report-configs configmap found at install time, using existing configs: configmaps "asset-report-configs" not found
I0315 10:21:08.561062       1 router.go:1452] No group-filters configmap found at install time, using existing configs: configmaps "group-filters" not found
I0315 10:21:08.564741       1 router.go:1454] Found configmap pricing-configs, watching...
I0315 10:21:08.570551       1 router.go:1452] No metrics-config configmap found at install time, using existing configs: configmaps "metrics-config" not found
I0315 10:21:08.750530       1 router.go:1454] Found configmap app-configs, watching...
I0315 10:21:08.950465       1 router.go:1452] No product-configs configmap found at install time, using existing configs: configmaps "product-configs" not found
I0315 10:21:09.150272       1 router.go:1454] Found configmap alert-configs, watching...
I0315 10:21:09.351365       1 router.go:1452] No saved-report-configs configmap found at install time, using existing configs: configmaps "saved-report-configs" not found
E0315 10:21:09.396593       1 log.go:17] [Error] operation error Athena: StartQueryExecution, failed to sign request: failed to retrieve credentials: operation error STS: AssumeRole, https response error StatusCode: 403, RequestID: [REDACTED], api error AccessDenied: User: arn:aws:iam::[REDACTED]:user/[REDACTED] is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::[REDACTED]:role/[REDACTED]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1891a56]

goroutine 1 [running]:
github.com/kubecost/cost-model/pkg/cloud.(*AWS).QueryAthenaPaginated(0x2176590, {0x2583fa0, 0xc00005a078}, {0xc000f78e10, 0x8b}, 0xc00107e070)
	/app/cost-model/pkg/cloud/awsprovider.go:1599 +0x416
github.com/kubecost/cost-model/pkg/cloud.(*AWS).fetchColumns(0x45084f)
	/app/cost-model/pkg/cloud/awsprovider.go:1831 +0x125
github.com/kubecost/cost-model/pkg/cloud.(*AWS).GetReservationDataFromAthena(0xc000d50400)
	/app/cost-model/pkg/cloud/awsprovider.go:1737 +0x65
github.com/kubecost/cost-model/pkg/cloud.(*AWS).DownloadPricingData(0xc000d50400)
	/app/cost-model/pkg/cloud/awsprovider.go:811 +0xf0b
github.com/kubecost/cost-model/pkg/costmodel.Initialize({0xc0009bf478, 0x6, 0x6})
	/app/cost-model/pkg/costmodel/router.go:1584 +0x213b
github.com/kubecost/kubecost-cost-model/pkg/cmd/costmodel.Initialize()
	/app/kubecost-cost-model/pkg/cmd/costmodel/costmodel.go:2942 +0x47c
github.com/kubecost/kubecost-cost-model/pkg/cmd/costmodel.Execute(0x0)
	/app/kubecost-cost-model/pkg/cmd/costmodel/costmodel.go:3176 +0x2e
github.com/kubecost/kubecost-cost-model/pkg/cmd.newCostModelCommand.func1(0xc00077e500, {0x20ce65b, 0x0, 0x0})
	/app/kubecost-cost-model/pkg/cmd/commands.go:30 +0x1d
github.com/spf13/cobra.(*Command).execute(0xc00077e500, {0x359f238, 0x0, 0x0})
	/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc00077e780)
	/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/kubecost/cost-model/pkg/cmd.Execute(0xc00005c060)
	/app/cost-model/pkg/cmd/commands.go:63 +0x325
github.com/kubecost/kubecost-cost-model/pkg/cmd.Execute()
	/app/kubecost-cost-model/pkg/cmd/commands.go:17 +0x1e
main.main()
	/app/kubecost-cost-model/cmd/costmodel/main.go:13 +0x19
```

**Comment by pierluigilenoci** [comment]
Similar error with v1.91.1. 

I tried to update because the new version exactly fixed a problem with Athena.
The message has changed slightly but the result has not changed.

```
I0315 10:25:09.257531       1 router.go:1319] Starting cost-model (git commit "1.91.1")
I0315 10:25:09.257643       1 router.go:1342] Prometheus/Thanos Client Max Concurrency set to 5
I0315 10:25:09.265648       1 router.go:1383] Success: retrieved the 'up' query against prometheus at: http://[REDACTED]
I0315 10:25:09.270554       1 router.go:1391] Retrieved a prometheus config file from: http://[REDACTED]
I0315 10:25:09.287431       1 router.go:1400] Using scrape interval of 60.000000
I0315 10:25:09.294741       1 clustercache.go:114] NAMESPACE: [REDACTED]
I0315 10:25:09.913304       1 clustercache.go:161] Done waiting
I0315 10:25:09.913851       1 watchcontroller.go:195] Starting *v1.Namespace controller
I0315 10:25:09.913908       1 watchcontroller.go:195] Starting *v1.Node controller
I0315 10:25:09.913931       1 watchcontroller.go:195] Starting *v1.Pod controller
I0315 10:25:09.914011       1 watchcontroller.go:195] Starting *v1.Service controller
I0315 10:25:09.914052       1 watchcontroller.go:195] Starting *v1.ConfigMap controller
I0315 10:25:09.914081       1 watchcontroller.go:195] Starting *v1.DaemonSet controller
I0315 10:25:09.914109       1 watchcontroller.go:195] Starting *v1.Deployment controller
I0315 10:25:09.914149       1 watchcontroller.go:195] Starting *v1.StatefulSet controller
I0315 10:25:09.914169       1 watchcontroller.go:195] Starting *v1.ReplicaSet controller
I0315 10:25:09.914305       1 watchcontroller.go:195] Starting *v1.PersistentVolume controller
I0315 10:25:09.914335       1 watchcontroller.go:195] Starting *v1.PersistentVolumeClaim controller
I0315 10:25:09.914363       1 watchcontroller.go:195] Starting *v1.StorageClass controller
I0315 10:25:09.914388       1 watchcontroller.go:195] Starting *v1.Job controller
I0315 10:25:09.914409       1 watchcontroller.go:195] Starting *v2beta1.HorizontalPodAutoscaler controller
I0315 10:25:09.914428       1 watchcontroller.go:195] Starting *v1beta1.PodDisruptionBudget controller
I0315 10:25:09.914448       1 watchcontroller.go:195] Starting *v1.ReplicationController controller
I0315 10:25:09.915291       1 provider.go:452] Found ProviderID starting with "aws", using AWS Provider
I0315 10:25:09.918958       1 router.go:1452] No product-configs configmap found at install time, using existing configs: configmaps "product-configs" not found
I0315 10:25:09.921897       1 router.go:1454] Found configmap alert-configs, watching...
I0315 10:25:09.937226       1 router.go:1452] No saved-report-configs configmap found at install time, using existing configs: configmaps "saved-report-configs" not found
I0315 10:25:09.967980       1 router.go:1452] No asset-report-configs configmap found at install time, using existing configs: configmaps "asset-report-configs" not found
I0315 10:25:10.117091       1 router.go:1452] No group-filters configmap found at install time, using existing configs: configmaps "group-filters" not found
I0315 10:25:10.317975       1 router.go:1454] Found configmap pricing-configs, watching...
I0315 10:25:10.518463       1 router.go:1452] No metrics-config configmap found at install time, using existing configs: configmaps "metrics-config" not found
I0315 10:25:10.717780       1 router.go:1454] Found configmap app-configs, watching...
E0315 10:25:10.776276       1 log.go:17] [Error] operation error Athena: StartQueryExecution, failed to sign request: failed to retrieve credentials: operation error STS: AssumeRole, https response error StatusCode: 403, RequestID: [REDACTED], api error AccessDenied: User: arn:aws:iam::[REDACTED]:user/[REDACTED] is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::[REDACTED]:role/[REDACTED]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1891b76]

goroutine 1 [running]:
github.com/kubecost/cost-model/pkg/cloud.(*AWS).QueryAthenaPaginated(0x2176769, {0x2584180, 0xc000066078}, {0xc000ea7200, 0x8b}, 0xc0012be070)
	/app/cost-model/pkg/cloud/awsprovider.go:1599 +0x416
github.com/kubecost/cost-model/pkg/cloud.(*AWS).fetchColumns(0x45084f)
	/app/cost-model/pkg/cloud/awsprovider.go:1842 +0x125
github.com/kubecost/cost-model/pkg/cloud.(*AWS).GetReservationDataFromAthena(0xc0010be400)
	/app/cost-model/pkg/cloud/awsprovider.go:1747 +0x65
github.com/kubecost/cost-model/pkg/cloud.(*AWS).DownloadPricingData(0xc0010be400)
	/app/cost-model/pkg/cloud/awsprovider.go:811 +0xf0b
github.com/kubecost/cost-model/pkg/costmodel.Initialize({0xc0008bf478, 0x6, 0x6})
	/app/cost-model/pkg/costmodel/router.go:1584 +0x213b
github.com/kubecost/kubecost-cost-model/pkg/cmd/costmodel.Initialize()
	/app/kubecost-cost-model/pkg/cmd/costmodel/costmodel.go:2942 +0x47c
github.com/kubecost/kubecost-cost-model/pkg/cmd/costmodel.Execute(0x0)
	/app/kubecost-cost-model/pkg/cmd/costmodel/costmodel.go:3176 +0x2e
github.com/kubecost/kubecost-cost-model/pkg/cmd.newCostModelCommand.func1(0xc00078d400, {0x20ce7db, 0x0, 0x0})
	/app/kubecost-cost-model/pkg/cmd/commands.go:30 +0x1d
github.com/spf13/cobra.(*Command).execute(0xc00078d400, {0x359f218, 0x0, 0x0})
	/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc00078d680)
	/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/kubecost/cost-model/pkg/cmd.Execute(0xc00005a060)
	/app/cost-model/pkg/cmd/commands.go:63 +0x325
github.com/kubecost/kubecost-cost-model/pkg/cmd.Execute()
	/app/kubecost-cost-model/pkg/cmd/commands.go:17 +0x1e
main.main()
	/app/kubecost-cost-model/cmd/costmodel/main.go:13 +0x19
```

**Comment by pierluigilenoci** [comment]
Of course, we haven't changed any of the AWS IAM side configurations.
The interesting thing is that 1.90.1 works and 1.91. * doesn't.

**Comment by AjayTripathy** [comment]
Thanks for the more detailed report @pierluigilenoci . This should never panic, but we did make a change to use sdkv2 that I will take a look at

**Comment by AjayTripathy** [comment]
Also-- you were able to access the AWS Athena SDK on v1.90.1? Were there cloud assets available on /assets.html?

**Comment by pierluigilenoci** [comment]
@AjayTripathy I'm sorry but I can't roll back to the previous version to check.
In the diagnostics tab, I hadn't detected problems in the past of integration with AWS, the costs were allocated correctly.

This cluster was updated yesterday from version 1.90.1 to 1.91.1. 

![Screenshot 2022-03-16 at 12 03 51](https://user-images.githubusercontent.com/36044817/158576276-a7b51e9c-6e83-4a9d-8688-de3848ee6732.png)

There are a couple of error reports on the diagnostics page but I don't think they are related to this.

![Screenshot 2022-03-16 at 12 04 11](https://user-images.githubusercontent.com/36044817/158576447-7c5c1016-94de-40a6-a99d-ce98b31da68e.png)

![Screenshot 2022-03-16 at 12 02 54](https://user-images.githubusercontent.com/36044817/158576246-8a73ae88-d1a9-4ca3-90fc-ae58b9973df7.png)

I take this opportunity to ask you if there are indications on how to solve them in your documentation.
Note: we have reserved EC2 instances and ES clusters so there should be some data. We don't use Spot instances instead.

Our config:
```yaml
kubecostProductConfigs:
  clusterProfile: high-availability
  athenaProjectID: [REDACTED]
  athenaBucketName: "s3://[REDACTED]"
  athenaRegion: eu-west-1
  athenaDatabase: [REDACTED]
  athenaTable: "[REDACTED]"
#      awsSpotDataRegion: eu-west-1
  masterPayerARN: "arn:aws:iam::[REDACTED]:role/[REDACTED]"
  projectID: "[REDACTED]"
```

We commented the `awsSpotDataRegion` value in an attempt to resolve the issue.

**Comment by pierluigilenoci** [comment]
@AjayTripathy I let myself be carried away by enthusiasm but if you want, for these further integration problems, I can open a new issue.

**Comment by AjayTripathy** [comment]
Yeah, happy to review other issues on integrations. But in the meantime we did publish v1.91.2 that should at least stop the pod from crashing. Mind revving the version and giving that a look when you can?

**Comment by kbrwn** [comment]
@pierluigilenoci did you have a change to upgrade to v1.91.2? Did this release fix issues with CUR access?

**Comment by pierluigilenoci** [comment]
@AjayTripathy @kbrwn the new version seems to have no problems with Athena.

**Comment by pierluigilenoci** [comment]
@AjayTripathy as you suggested I created #1128

**Comment by kbrwn** [comment]
@pierluigilenoci Thanks for creating another issue about spot. I agree that there should be an option to disable the diagnostic when not relevant. 

In regards to this issue, I believe it was resolved by v1.92.2, is this correct? If so I will close this. Let me know.

**Comment by pierluigilenoci** [comment]
@kbrwn yes, this is solved.

**Comment by kbrwn** [comment]
@pierluigilenoci Thanks for confirming!
