### ISSUE TITLE
CSV Export Panics When No Metrics Available

### ISSUE THREAD

**Issue by AjayTripathy** [opencost/opencost#1877]
**Describe the bug**
In the case where the CSV uploader initializes without node_cpu_hourly_cost available, there is a panic trying to determine the start time of the CSV
```
goroutine 376 [running]:
[github.com/opencost/opencost/pkg/costmodel.(*CostModel).DateRange(0x40011ccd20?)](http://github.com/opencost/opencost/pkg/costmodel.(*CostModel).DateRange(0x40011ccd20?))
    /app/pkg/costmodel/allocation.go:293 +0x2c0
[github.com/opencost/opencost/pkg/costmodel.(*csvExporter).availableAllocationDates(0x4000100400?)](http://github.com/opencost/opencost/pkg/costmodel.(*csvExporter).availableAllocationDates(0x4000100400?))
    /app/pkg/costmodel/csv_export.go:132 +0x2c
[github.com/opencost/opencost/pkg/costmodel.(*csvExporter).Update](http://github.com/opencost/opencost/pkg/costmodel.(*csvExporter).Update)(0x4000e55f88, {0x27d8970, 0x4000058018})
    /app/pkg/costmodel/csv_export.go:41 +0x34
[github.com/opencost/opencost/pkg/costmodel.UpdateCSV(...)](http://github.com/opencost/opencost/pkg/costmodel.UpdateCSV(...))
    /app/pkg/costmodel/csv_export.go:31
[github.com/opencost/opencost/pkg/cmd/costmodel.StartExportWorker.func1()](http://github.com/opencost/opencost/pkg/cmd/costmodel.StartExportWorker.func1())
    /app/pkg/cmd/costmodel/costmodel.go:74 +0x1a4
created by [github.com/opencost/opencost/pkg/cmd/costmodel.StartExportWorker](http://github.com/opencost/opencost/pkg/cmd/costmodel.StartExportWorker)
    /app/pkg/cmd/costmodel/costmodel.go:64 +0x130
```

**To Reproduce**
Run OpenCost with the CSV Exporter enabled 

**Expected behavior**
No panic-- an error log explaining this would be great, though.

**Which version of OpenCost are you using?**
kc-eu-2023

**Comment by mattray** [comment]
@r2k1 FYI

**Comment by AjayTripathy** [comment]
https://github.com/opencost/opencost/blob/develop/pkg/costmodel/allocation.go#L293

This and below -- access should be guarded to [0] element of list, and errors should be clearly logged when the CSV Export function is called and we encounter this edge case.
